--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/brokiem-pm-pl/Sobana
build-by-default: true
branches:
- master
projects:
  Sobana:
    path: ""
    model: virion
    type: library
...
